const { chromium } = require('playwright');
const URL = process.env.CUTLOOM_URL || 'https://cutloom-demo.vercel.app';
(async () => {
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror',e=>errors.push(String(e)));
  page.on('console',m=>{if(m.type()==='error') errors.push(m.text())});
  const response = await page.goto(URL,{waitUntil:'networkidle'});
  if (!response || !response.ok()) throw new Error(`Live URL returned ${response?.status() ?? 'no response'}`);
  await page.waitForSelector('#canvas');
  if (!(await page.title()).includes('Launch Reel')) throw new Error('Unexpected title');
  const sceneCountText = (await page.locator('#sceneCount').textContent()).trim();
  console.log('CUTLOOM_STATE', JSON.stringify({title: await page.title(), sceneCountText, bodyStart: (await page.locator('body').innerText()).slice(0,240)}));
  if (sceneCountText !== '6 scenes') throw new Error(`Demo scenes missing: ${JSON.stringify(sceneCountText)}`);
  await page.getByRole('button',{name:'Scenes'}).click();
  await page.waitForSelector('#storyGrid .scene-card');
  if (await page.locator('#storyGrid .scene-card').count() !== 6) throw new Error('Storyboard did not render');
  await page.locator('#storyGrid .scene-card').nth(2).click();
  await page.locator('#titleInput').fill('A changed scene title');
  if ((await page.locator('#previewTitle').innerText()) !== 'A changed scene title') throw new Error('Inspector did not update preview');
  await page.getByRole('button',{name:'Portrait'}).click();
  if (!(await page.locator('#canvas').evaluate(el=>el.classList.contains('canvas-portrait')))) throw new Error('Portrait mode failed');
  await page.getByRole('button',{name:/Add scene/}).click();
  if ((await page.locator('#sceneCount').innerText()) !== '7 scenes') throw new Error('Add scene failed');
  await page.getByRole('button',{name:'Export'}).click();
  const dl = await Promise.all([page.waitForEvent('download'), page.locator('#csvBtn').click()]);
  if (!dl[0].suggestedFilename().endsWith('.csv')) throw new Error('CSV export failed');
  const media = await page.evaluate(() => ({mediaRecorder: !!window.MediaRecorder, captureStream: !!HTMLCanvasElement.prototype.captureStream}));
  if (!media.mediaRecorder || !media.captureStream) console.warn('WebM render APIs unavailable in browser environment', media);
  if (errors.length) throw new Error('Browser errors: '+errors.join(' | '));
  console.log('CUTLOOM_SMOKE_OK', JSON.stringify({url:URL,media,scenes:7}));
  await browser.close();
})().catch(err=>{console.error(err); process.exit(1)});
